
@baseUrl = https://localhost:5001
###@baseUrl = http://interviewerapi-env-1.eba-acpmepbh.ap-southeast-2.elasticbeanstalk.com

### Get all personal questions
GET {{baseUrl}}/question-bank
Content-Type: application/json


### Get all personal questions in a category
GET {{baseUrl}}/question-bank/JavaScript
Content-Type: application/json


### Save new question
POST {{baseUrl}}/question-bank/question
Content-Type: application/json

{
    "category": "C#",
    "question": "Explain in detail the finalize method in C#?",
    "tags": ["fundamentals"],
    "time": 2
}

### Update question

PUT {{baseUrl}}/question-bank/question
Content-Type: application/json

{
    "questionId": "7bab9df9-3b35-4661-a8a4-03c6fa6aeb98",
    "category": "JavaScript",
    "question": "Can you name two programming paradigms important for JavaScript app developers?",
    "tags": ["concepts"],
    "time": 5
}

### Delete question

@questionId = 7bab9df9-3b35-4661-a8a4-03c6fa6aeb98

DELETE {{baseUrl}}/question-bank/question/{{questionId}}
Content-Type: application/json