
@baseUrl = https://localhost:5001
###@baseUrl = http://interviewerapi-env-1.eba-acpmepbh.ap-southeast-2.elasticbeanstalk.com
###@baseUrl = https://api.interviewer.space
@token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InhJQUpFVVpoWm0tWE5DNVdTNzlNRiJ9.eyJpc3MiOiJodHRwczovL2ludGVydmlld2VyLmF1LmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwMDYxMzUzOTA5OTUxNDYwMTM0NiIsImF1ZCI6WyJodHRwOi8vaW50ZXJ2aWV3ZXJhcGktZW52LTEuZWJhLWFjcG1lcGJoLmFwLXNvdXRoZWFzdC0yLmVsYXN0aWNiZWFuc3RhbGsuY29tIiwiaHR0cHM6Ly9pbnRlcnZpZXdlci5hdS5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjIwNzk0NDAxLCJleHAiOjE2MjA4ODA4MDEsImF6cCI6InQ5NVNGVHZrelJNaWlHajhoTFNUSUtDRXdyQzV3ZmEwIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCJ9.IV_hbnbY_46OuGW5TEwY5708rIC__huJmLiDrQgJzGVKBA7-gBjHg8dy-usKf6P5-80nM9AD6NLOjAq-i22BjvboVq4YQqEoVxpEOGFK9s76ZP7d0u37LGBdD1QREZeLPw7lhHtKyXt_P-5TQxddIEoG2JxkQTtivJAdWeYbkbuaELJC-5AyBJMfOxo9jViUBWLfbHo6KwsFcyybMfHaXGD-Jhqbpul5Z__IdJ3MCQobPnGizXyOhU0SFBuFlmAg6TkLjU_mL2Bi-e_y4YAa9WbogQdm8HPk46FZJlO3xjzxY6RxrfyXyTsY--2NQcqtaqqavrzZ2r-r12_PmO5MnA


### Add new category
POST {{baseUrl}}/question-bank/category
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "categoryName": "Scala"   
}

### Delete category
DELETE {{baseUrl}}/question-bank/category/d680f535-9ab0-4297-b1e5-66e5bd719d6d
Content-Type: application/json
Authorization: Bearer {{token}}


### Get all personal questions (NEW)
GET {{baseUrl}}/question-bank/new
Content-Type: application/json
Authorization: Bearer {{token}}

### Get all personal questions
GET {{baseUrl}}/question-bank
Content-Type: application/json
Authorization: Bearer {{token}}

### Get all personal questions in a category
GET {{baseUrl}}/question-bank/C%23
Content-Type: application/json
Authorization: Bearer {{token}}

### Save new question
POST {{baseUrl}}/question-bank
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "category": "JavaScript",
    "question": "What is the significance of, and reason for, wrapping the entire content of a JavaScript source file in a function block?",
    "tags": ["fundamentals"],
    "time": 5
}

### Update question

PUT {{baseUrl}}/question-bank
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "questionId": "7bab9df9-3b35-4661-a8a4-03c6fa6aeb98",
    "category": "JavaScript",
    "question": "Can you name two programming paradigms important for JavaScript app developers?",
    "tags": ["concepts"],
    "time": 5
}

### Delete question

@questionId = 7bab9df9-3b35-4661-a8a4-03c6fa6aeb98

DELETE {{baseUrl}}/question-bank/{{questionId}}
Content-Type: application/json
Authorization: Bearer {{token}}