
@baseUrl = https://localhost:5001
###@baseUrl = http://interviewerapi-env-1.eba-acpmepbh.ap-southeast-2.elasticbeanstalk.com
###@baseUrl = https://api.interviewer.space
@token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InhJQUpFVVpoWm0tWE5DNVdTNzlNRiJ9.eyJpc3MiOiJodHRwczovL2ludGVydmlld2VyLmF1LmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwMDYxMzUzOTA5OTUxNDYwMTM0NiIsImF1ZCI6WyJodHRwOi8vaW50ZXJ2aWV3ZXJhcGktZW52LTEuZWJhLWFjcG1lcGJoLmFwLXNvdXRoZWFzdC0yLmVsYXN0aWNiZWFuc3RhbGsuY29tIiwiaHR0cHM6Ly9pbnRlcnZpZXdlci5hdS5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjE5ODQ3NzgzLCJleHAiOjE2MTk5MzQxODMsImF6cCI6InQ5NVNGVHZrelJNaWlHajhoTFNUSUtDRXdyQzV3ZmEwIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCJ9.cWQ_bgeiC-YY2dwW-Vrkeoa21V1adxV4EqS989eYufgGRKWkgD85bfbWSg-h0b3_Y_xJ6DSvBIs27xew6yjy4b6TMt2wX-mXDaT6cQZQQYCBFClWFk7TcmsuUIKemtrfL-3vKCIQqzzXA00YIytWiIIHNHCSHzeY0LVbFoc8iM2niKFdbSH3MfmU0X173i-1Ib-pjnxWXPATLomlJ0pYTcdwX5r4axaZWABFxiCgq9xL9ugFfZ-z_hjbv5rWQKNla0uzc-FRI5GZKuNjOkjt7v5YfCFzdI416-8cJhbYir7Hiv9taLfHWK7vAAnTGsOtu19--dz7Eb7EuEGI5aXFCg


### Add new category
POST {{baseUrl}}/question-bank/category
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "categoryName": "Scala"   
}

### Get all personal questions (NEW)
GET {{baseUrl}}/question-bank/new
Content-Type: application/json
Authorization: Bearer {{token}}

### Get all personal questions
GET {{baseUrl}}/question-bank
Content-Type: application/json
Authorization: Bearer {{token}}

### Get all personal questions in a category
GET {{baseUrl}}/question-bank/C%23
Content-Type: application/json
Authorization: Bearer {{token}}

### Save new question
POST {{baseUrl}}/question-bank
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "category": "JavaScript",
    "question": "What is the significance of, and reason for, wrapping the entire content of a JavaScript source file in a function block?",
    "tags": ["fundamentals"],
    "time": 5
}

### Update question

PUT {{baseUrl}}/question-bank
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "questionId": "7bab9df9-3b35-4661-a8a4-03c6fa6aeb98",
    "category": "JavaScript",
    "question": "Can you name two programming paradigms important for JavaScript app developers?",
    "tags": ["concepts"],
    "time": 5
}

### Delete question

@questionId = 7bab9df9-3b35-4661-a8a4-03c6fa6aeb98

DELETE {{baseUrl}}/question-bank/{{questionId}}
Content-Type: application/json
Authorization: Bearer {{token}}