
@baseUrl = https://localhost:5001
###@baseUrl = http://interviewerapi-env-1.eba-acpmepbh.ap-southeast-2.elasticbeanstalk.com
###@baseUrl = https://api.interviewer.space
@token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InhJQUpFVVpoWm0tWE5DNVdTNzlNRiJ9.eyJpc3MiOiJodHRwczovL2ludGVydmlld2VyLmF1LmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwMDYxMzUzOTA5OTUxNDYwMTM0NiIsImF1ZCI6WyJodHRwOi8vaW50ZXJ2aWV3ZXJhcGktZW52LTEuZWJhLWFjcG1lcGJoLmFwLXNvdXRoZWFzdC0yLmVsYXN0aWNiZWFuc3RhbGsuY29tIiwiaHR0cHM6Ly9pbnRlcnZpZXdlci5hdS5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjIwNzgwMjY4LCJleHAiOjE2MjA4NjY2NjgsImF6cCI6InQ5NVNGVHZrelJNaWlHajhoTFNUSUtDRXdyQzV3ZmEwIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCJ9.sPIA2tIxvIQJ1ZJMEnowWA5v83GRHOThzp1zeUPvYac7IYGqEeaDGRn3T9aSLZS9lj7IX1-JK3zVFl3O1Pffy9UmtitoOaOQ66WTCzIjnz37yF2cFcy9fXaeTnEf0sG21tCQuRvbC5J0y3lGYDvl-CE2E9d0nrjbWh0sBR_7ojDInJ3hOAm4RA3qk0yU1Z6yQaH4OBCWnHYyP8rEtStZeJcG2hwFsmAoDbcPLHhqGBgHbCdBZU1aTXW0YPcNArgTkk2GXts4bwwV42sp0RlkAvbBeYleBhQDChw5DDM0u6HsRKH4rIcBaAbHSAgpsLPwu1jT8Xm8-jrh0JOfQnbM_g


### Add new category
POST {{baseUrl}}/question-bank/category
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "categoryName": "Scala"   
}

### Delete category
DELETE {{baseUrl}}/question-bank/category/efc24ce4-7c38-41f6-89c7-37ffd4858446
Content-Type: application/json
Authorization: Bearer {{token}}


### Get all personal questions (NEW)
GET {{baseUrl}}/question-bank/new
Content-Type: application/json
Authorization: Bearer {{token}}

### Get all personal questions
GET {{baseUrl}}/question-bank
Content-Type: application/json
Authorization: Bearer {{token}}

### Get all personal questions in a category
GET {{baseUrl}}/question-bank/C%23
Content-Type: application/json
Authorization: Bearer {{token}}

### Save new question
POST {{baseUrl}}/question-bank
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "category": "JavaScript",
    "question": "What is the significance of, and reason for, wrapping the entire content of a JavaScript source file in a function block?",
    "tags": ["fundamentals"],
    "time": 5
}

### Update question

PUT {{baseUrl}}/question-bank
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "questionId": "7bab9df9-3b35-4661-a8a4-03c6fa6aeb98",
    "category": "JavaScript",
    "question": "Can you name two programming paradigms important for JavaScript app developers?",
    "tags": ["concepts"],
    "time": 5
}

### Delete question

@questionId = 7bab9df9-3b35-4661-a8a4-03c6fa6aeb98

DELETE {{baseUrl}}/question-bank/{{questionId}}
Content-Type: application/json
Authorization: Bearer {{token}}