
@baseUrl = https://localhost:5001
#@baseUrl = https://api.interviewer.space
@token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InhJQUpFVVpoWm0tWE5DNVdTNzlNRiJ9.eyJpc3MiOiJodHRwczovL2ludGVydmlld2VyLmF1LmF1dGgwLmNvbS8iLCJzdWIiOiJheW5TektwQXkzVjZmVXpQZnc4bWd0b3JSUUtVc2F4RkBjbGllbnRzIiwiYXVkIjoiaHR0cDovL2ludGVydmlld2VyYXBpLWVudi0xLmViYS1hY3BtZXBiaC5hcC1zb3V0aGVhc3QtMi5lbGFzdGljYmVhbnN0YWxrLmNvbSIsImlhdCI6MTYxNDY3MDIzNiwiZXhwIjoxNjE0NzU2NjM2LCJhenAiOiJheW5TektwQXkzVjZmVXpQZnc4bWd0b3JSUUtVc2F4RiIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.nCgouri-vXEkf4KQnfuMXZx6t-2UKiWiFI4CWvYBYwHGoamR7VIsNA4rPDm2LMAdmSmGxLkPcQf0hOn0r5apLZ4zLNGq_DxWAvE8eiJJfzak4S5mWes0Fcb-X5MNhL5vxMhDWbGmkJ7ArJ0zhWwOc-lBJxPW_rRUbbibHWs09rBjZfv9l6Mt8Q-ZsNE2Xp5aKdwvMKvGOSB9hF1nsV6WaJBFmPwdiLlXUpMvf1Yjg0vgUelzCJj6anPHmnr9X0fCI3COIVW-VaWrFO7yYhru5acnqB86Z7codfodrBdRHWBvr1tXvq73BjF-_hX8KX3wgIhDGeawCG9d9GpRuNXiFA


### Get all community categories
GET {{baseUrl}}/community/categories
Content-Type: application/json
Authorization: Bearer {{token}}

### Create a category
POST {{baseUrl}}/community/category
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "categoryName": "Dart",
    "image": "https://pbs.twimg.com/profile_images/993555605078994945/Yr-pWI4G_400x400.jpg"
}

### Create a category
POST {{baseUrl}}/community/contribute
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "personalQuestionId": "682f57a7-a17d-439a-88ff-877a9291ee6e",
    "communityCategoryId": "04088f02-0193-4174-b2a4-d8db14bd7686"
}